mysql:
  binlog:
    switch: true

trans:
  db:
    mysql:
      dataSource:
        could:
          host: cdb-ahs4c0jv.gz.tencentcdb.com
          port: 10050
          username: root
          password: dazhi-1993aini
